# -*- coding: utf-8 -*-
"""Market_Data_Extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K6aGq96sTpMuExQ0bBiU-ji73Ze9XTfR
"""

import yfinance as yf
import pandas as pd

# List of real Macquarie-relevant tickers
tickers = [ 'BHP.AX', 'RIO.AX', 'WDS.AX', 'WBC.AX', 'TLS.AX',
    'CBA.AX', 'NAB.AX', 'ANZ.AX', 'MQG.AX', 'FMG.AX',
    'CSL.AX', 'WOW.AX', 'TCL.AX', 'ASX.AX', 'XRO.AX']

def get_real_market_data(ticker_list):
    real_data = []

    for symbol in ticker_list:
        print(f"Fetching data for {symbol}...")
        ticker = yf.Ticker(symbol)
        info = ticker.info

        # PCAF requires EVIC (Enterprise Value)
        # yfinance provides 'enterpriseValue'
        evic = info.get('enterpriseValue')
        revenue = info.get('totalRevenue')
        name = info.get('longName')

        real_data.append({
            'Ticker': symbol,
            'Real_Company_Name': name,
            'EVIC_AUD': evic,
            'Total_Revenue_AUD': revenue
        })

    return pd.DataFrame(real_data)

# Execute
df_real = get_real_market_data(tickers)

# Save this to a 'Real_Market_Data.csv'
df_real.to_csv('Real_Market_Data.csv', index=False)
print("Real data saved! Now you can use this to replace rows in your ledger.")
print(df_real)